export const zipCodes = [
  // Major US Cities and ZIP Codes
  { zip: '10001', city: 'New York', state: 'NY' },
  { zip: '10002', city: 'New York', state: 'NY' },
  { zip: '10003', city: 'New York', state: 'NY' },
  { zip: '10004', city: 'New York', state: 'NY' },
  { zip: '10005', city: 'New York', state: 'NY' },
  { zip: '90001', city: 'Los Angeles', state: 'CA' },
  { zip: '90002', city: 'Los Angeles', state: 'CA' },
  { zip: '90003', city: 'Los Angeles', state: 'CA' },
  { zip: '90004', city: 'Los Angeles', state: 'CA' },
  { zip: '90005', city: 'Los Angeles', state: 'CA' },
  { zip: '60601', city: 'Chicago', state: 'IL' },
  { zip: '60602', city: 'Chicago', state: 'IL' },
  { zip: '60603', city: 'Chicago', state: 'IL' },
  { zip: '60604', city: 'Chicago', state: 'IL' },
  { zip: '60605', city: 'Chicago', state: 'IL' },
  { zip: '77001', city: 'Houston', state: 'TX' },
  { zip: '77002', city: 'Houston', state: 'TX' },
  { zip: '77003', city: 'Houston', state: 'TX' },
  { zip: '77004', city: 'Houston', state: 'TX' },
  { zip: '77005', city: 'Houston', state: 'TX' },
  { zip: '85001', city: 'Phoenix', state: 'AZ' },
  { zip: '85002', city: 'Phoenix', state: 'AZ' },
  { zip: '85003', city: 'Phoenix', state: 'AZ' },
  { zip: '85004', city: 'Phoenix', state: 'AZ' },
  { zip: '85005', city: 'Phoenix', state: 'AZ' },
  { zip: '19101', city: 'Philadelphia', state: 'PA' },
  { zip: '19102', city: 'Philadelphia', state: 'PA' },
  { zip: '19103', city: 'Philadelphia', state: 'PA' },
  { zip: '19104', city: 'Philadelphia', state: 'PA' },
  { zip: '19105', city: 'Philadelphia', state: 'PA' },
  { zip: '78201', city: 'San Antonio', state: 'TX' },
  { zip: '78202', city: 'San Antonio', state: 'TX' },
  { zip: '78203', city: 'San Antonio', state: 'TX' },
  { zip: '78204', city: 'San Antonio', state: 'TX' },
  { zip: '78205', city: 'San Antonio', state: 'TX' },
  { zip: '92101', city: 'San Diego', state: 'CA' },
  { zip: '92102', city: 'San Diego', state: 'CA' },
  { zip: '92103', city: 'San Diego', state: 'CA' },
  { zip: '92104', city: 'San Diego', state: 'CA' },
  { zip: '92105', city: 'San Diego', state: 'CA' },
  { zip: '75201', city: 'Dallas', state: 'TX' },
  { zip: '75202', city: 'Dallas', state: 'TX' },
  { zip: '75203', city: 'Dallas', state: 'TX' },
  { zip: '75204', city: 'Dallas', state: 'TX' },
  { zip: '95101', city: 'San Jose', state: 'CA' },
  { zip: '95102', city: 'San Jose', state: 'CA' },
  { zip: '95103', city: 'San Jose', state: 'CA' },
  { zip: '78701', city: 'Austin', state: 'TX' },
  { zip: '78702', city: 'Austin', state: 'TX' },
  { zip: '78703', city: 'Austin', state: 'TX' },
  { zip: '32801', city: 'Jacksonville', state: 'FL' },
  { zip: '32802', city: 'Jacksonville', state: 'FL' },
  { zip: '43201', city: 'Columbus', state: 'OH' },
  { zip: '43202', city: 'Columbus', state: 'OH' },
  { zip: '76101', city: 'Fort Worth', state: 'TX' },
  { zip: '76102', city: 'Fort Worth', state: 'TX' },
  { zip: '28201', city: 'Charlotte', state: 'NC' },
  { zip: '28202', city: 'Charlotte', state: 'NC' },
  { zip: '94101', city: 'San Francisco', state: 'CA' },
  { zip: '94102', city: 'San Francisco', state: 'CA' },
  { zip: '94103', city: 'San Francisco', state: 'CA' },
  { zip: '46201', city: 'Indianapolis', state: 'IN' },
  { zip: '46202', city: 'Indianapolis', state: 'IN' },
  { zip: '98101', city: 'Seattle', state: 'WA' },
  { zip: '98102', city: 'Seattle', state: 'WA' },
  { zip: '98103', city: 'Seattle', state: 'WA' },
  { zip: '80201', city: 'Denver', state: 'CO' },
  { zip: '80202', city: 'Denver', state: 'CO' },
  { zip: '80203', city: 'Denver', state: 'CO' },
  { zip: '20001', city: 'Washington', state: 'DC' },
  { zip: '20002', city: 'Washington', state: 'DC' },
  { zip: '20003', city: 'Washington', state: 'DC' },
  { zip: '02101', city: 'Boston', state: 'MA' },
  { zip: '02102', city: 'Boston', state: 'MA' },
  { zip: '02103', city: 'Boston', state: 'MA' },
  { zip: '38101', city: 'Memphis', state: 'TN' },
  { zip: '38102', city: 'Memphis', state: 'TN' },
  { zip: '37201', city: 'Nashville', state: 'TN' },
  { zip: '37202', city: 'Nashville', state: 'TN' },
  { zip: '97201', city: 'Portland', state: 'OR' },
  { zip: '97202', city: 'Portland', state: 'OR' },
  { zip: '73101', city: 'Oklahoma City', state: 'OK' },
  { zip: '73102', city: 'Oklahoma City', state: 'OK' },
  { zip: '89101', city: 'Las Vegas', state: 'NV' },
  { zip: '89102', city: 'Las Vegas', state: 'NV' },
  { zip: '89103', city: 'Las Vegas', state: 'NV' },
  { zip: '40201', city: 'Louisville', state: 'KY' },
  { zip: '40202', city: 'Louisville', state: 'KY' },
  { zip: '53201', city: 'Milwaukee', state: 'WI' },
  { zip: '53202', city: 'Milwaukee', state: 'WI' },
  { zip: '87101', city: 'Albuquerque', state: 'NM' },
  { zip: '87102', city: 'Albuquerque', state: 'NM' },
  { zip: '85201', city: 'Tucson', state: 'AZ' },
  { zip: '85202', city: 'Tucson', state: 'AZ' },
  { zip: '30301', city: 'Atlanta', state: 'GA' },
  { zip: '30302', city: 'Atlanta', state: 'GA' },
  { zip: '30303', city: 'Atlanta', state: 'GA' },
  { zip: '23501', city: 'Virginia Beach', state: 'VA' },
  { zip: '23502', city: 'Virginia Beach', state: 'VA' },
  { zip: '68101', city: 'Omaha', state: 'NE' },
  { zip: '68102', city: 'Omaha', state: 'NE' },
  { zip: '33101', city: 'Miami', state: 'FL' },
  { zip: '33102', city: 'Miami', state: 'FL' },
  { zip: '33103', city: 'Miami', state: 'FL' },
  { zip: '44101', city: 'Cleveland', state: 'OH' },
  { zip: '44102', city: 'Cleveland', state: 'OH' },
  { zip: '70112', city: 'New Orleans', state: 'LA' },
  { zip: '70113', city: 'New Orleans', state: 'LA' },
  { zip: '96801', city: 'Honolulu', state: 'HI' },
  { zip: '96802', city: 'Honolulu', state: 'HI' },
  { zip: '55401', city: 'Minneapolis', state: 'MN' },
  { zip: '55402', city: 'Minneapolis', state: 'MN' },
  { zip: '33601', city: 'Tampa', state: 'FL' },
  { zip: '33602', city: 'Tampa', state: 'FL' },
  { zip: '35201', city: 'Birmingham', state: 'AL' },
  { zip: '35202', city: 'Birmingham', state: 'AL' },
  { zip: '21201', city: 'Baltimore', state: 'MD' },
  { zip: '21202', city: 'Baltimore', state: 'MD' },
  { zip: '63101', city: 'St. Louis', state: 'MO' },
  { zip: '63102', city: 'St. Louis', state: 'MO' },
  { zip: '64101', city: 'Kansas City', state: 'MO' },
  { zip: '64102', city: 'Kansas City', state: 'MO' },
  { zip: '15201', city: 'Pittsburgh', state: 'PA' },
  { zip: '15202', city: 'Pittsburgh', state: 'PA' },
  { zip: '45201', city: 'Cincinnati', state: 'OH' },
  { zip: '45202', city: 'Cincinnati', state: 'OH' },
  { zip: '99501', city: 'Anchorage', state: 'AK' },
  { zip: '99502', city: 'Anchorage', state: 'AK' },
  { zip: '84101', city: 'Salt Lake City', state: 'UT' },
  { zip: '84102', city: 'Salt Lake City', state: 'UT' },
  { zip: '27601', city: 'Raleigh', state: 'NC' },
  { zip: '27602', city: 'Raleigh', state: 'NC' },
  { zip: '12201', city: 'Albany', state: 'NY' },
  { zip: '12202', city: 'Albany', state: 'NY' },
  { zip: '14201', city: 'Buffalo', state: 'NY' },
  { zip: '14202', city: 'Buffalo', state: 'NY' },
  { zip: '48201', city: 'Detroit', state: 'MI' },
  { zip: '48202', city: 'Detroit', state: 'MI' },
  { zip: '48203', city: 'Detroit', state: 'MI' },
  { zip: '49501', city: 'Grand Rapids', state: 'MI' },
  { zip: '49502', city: 'Grand Rapids', state: 'MI' },
  { zip: '50301', city: 'Des Moines', state: 'IA' },
  { zip: '50302', city: 'Des Moines', state: 'IA' },
  { zip: '59101', city: 'Billings', state: 'MT' },
  { zip: '59102', city: 'Billings', state: 'MT' },
  { zip: '58501', city: 'Bismarck', state: 'ND' },
  { zip: '58502', city: 'Bismarck', state: 'ND' },
  { zip: '57501', city: 'Sioux Falls', state: 'SD' },
  { zip: '57502', city: 'Sioux Falls', state: 'SD' },
  { zip: '82001', city: 'Cheyenne', state: 'WY' },
  { zip: '82002', city: 'Cheyenne', state: 'WY' },
  { zip: '83201', city: 'Pocatello', state: 'ID' },
  { zip: '83202', city: 'Pocatello', state: 'ID' },
];